import React from 'react';
import {
  LayoutDashboard,
  Box,
  RefreshCw,
  Users,
  Truck,
  CreditCard,
  ShoppingBag,
  TrendingUp,
  ShoppingCart,
  BarChart3,
  TrendingDown,
  Scale,
  BookOpen,
  Shield,
  Settings,
  Lock,
  FileText,
  Database,
  Binary
} from 'lucide-react';

export interface ModuleDefinition {
  readonly id: string;
  readonly displayName: string;
  readonly icon: React.ComponentType<{ className?: string }>;
  readonly routeKey?: string; // Key used for activeTab / navigation routes
  readonly collectionNames: readonly string[]; // Firestore collection(s) used by the module
  readonly isSingleton?: boolean;
  readonly singletonDocId?: string; // If singleton, e.g. 'config', 'bootstrap'
  readonly backupPath?: string; // Path inside backup zip, e.g. 'security/users.json'
  readonly category: 'Configuration' | 'Security' | 'Master Data' | 'Transactions' | 'Accounting' | 'System' | 'Core';
  readonly permissions?: {
    readonly view?: string; // e.g. 'viewExpenses', 'viewUsers'
    readonly manage?: string; // e.g. 'manageSettings', 'createCustomer'
  };
  readonly dependencies: readonly string[]; // Dependent module IDs
  readonly supportsBackup: boolean;
  readonly supportsRestore: boolean;
  readonly supportsDashboard: boolean;
  readonly supportsSearch: boolean;
  readonly supportsReports: boolean;
  readonly visibleInNavigation: boolean;
  readonly navigationOrder?: number;
}

export const MODULE_REGISTRY: readonly ModuleDefinition[] = [
  // --- CONFIGURATION MODULES ---
  {
    id: 'businessProfile/config',
    displayName: 'Business Profile',
    icon: Settings,
    collectionNames: ['businessProfile'],
    isSingleton: true,
    singletonDocId: 'config',
    backupPath: 'config/businessProfile.json',
    category: 'Configuration',
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'system/bootstrap',
    displayName: 'System Bootstrap',
    icon: Settings,
    collectionNames: ['system'],
    isSingleton: true,
    singletonDocId: 'bootstrap',
    backupPath: 'config/system.json',
    category: 'Configuration',
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },

  // --- SECURITY MODULES ---
  {
    id: 'users',
    displayName: 'User Access',
    icon: Shield,
    routeKey: 'users',
    collectionNames: ['users'],
    backupPath: 'security/users.json',
    category: 'Security',
    permissions: { view: 'viewUsers', manage: 'manageUsers' },
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: true,
    supportsReports: false,
    visibleInNavigation: true,
    navigationOrder: 140,
  },
  {
    id: 'rolePermissions',
    displayName: 'Role Permissions',
    icon: Lock,
    collectionNames: ['rolePermissions'],
    backupPath: 'security/rolePermissions.json',
    category: 'Security',
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },

  // --- MASTER DATA MODULES ---
  {
    id: 'customers',
    displayName: 'Customers',
    icon: Users,
    routeKey: 'customers',
    collectionNames: ['customers'],
    backupPath: 'master-data/customers.json',
    category: 'Master Data',
    permissions: { view: 'viewCustomers', manage: 'createCustomer' },
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: true,
    supportsSearch: true,
    supportsReports: true,
    visibleInNavigation: true,
    navigationOrder: 40,
  },
  {
    id: 'suppliers',
    displayName: 'Suppliers',
    icon: Truck,
    routeKey: 'suppliers',
    collectionNames: ['suppliers'],
    backupPath: 'master-data/suppliers.json',
    category: 'Master Data',
    permissions: { view: 'viewSuppliers', manage: 'createSupplier' },
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: true,
    supportsSearch: true,
    supportsReports: true,
    visibleInNavigation: true,
    navigationOrder: 50,
  },
  {
    id: 'products',
    displayName: 'Products',
    icon: ShoppingBag,
    routeKey: 'products',
    collectionNames: ['products'],
    backupPath: 'master-data/products.json',
    category: 'Master Data',
    permissions: { view: 'viewProducts', manage: 'canEditProduct' },
    dependencies: ['suppliers'],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: true,
    supportsSearch: true,
    supportsReports: true,
    visibleInNavigation: true,
    navigationOrder: 70,
  },
  {
    id: 'items',
    displayName: 'Items',
    icon: Box,
    collectionNames: ['items'],
    backupPath: 'master-data/items.json',
    category: 'Master Data',
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'expenseCategories',
    displayName: 'Expense Categories',
    icon: FileText,
    collectionNames: ['expenseCategories'],
    backupPath: 'master-data/expenseCategories.json',
    category: 'Master Data',
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'chartOfAccounts',
    displayName: 'Chart of Accounts',
    icon: BookOpen,
    routeKey: 'chart_of_accounts',
    collectionNames: ['chartOfAccounts'],
    backupPath: 'master-data/chartOfAccounts.json',
    category: 'Master Data',
    permissions: { view: 'viewSettings', manage: 'manageSettings' },
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: true,
    supportsSearch: true,
    supportsReports: true,
    visibleInNavigation: true,
    navigationOrder: 130,
  },

  // --- TRANSACTIONS MODULES ---
  {
    id: 'sales',
    displayName: 'Sales',
    icon: TrendingUp,
    routeKey: 'sales',
    collectionNames: ['sales'],
    backupPath: 'transactions/sales.json',
    category: 'Transactions',
    permissions: { view: 'viewSales', manage: 'createSale' },
    dependencies: ['customers', 'products', 'chartOfAccounts'],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: true,
    supportsSearch: true,
    supportsReports: true,
    visibleInNavigation: true,
    navigationOrder: 80,
  },
  {
    id: 'purchases',
    displayName: 'Purchases',
    icon: ShoppingCart,
    routeKey: 'procurement',
    collectionNames: ['purchases'],
    backupPath: 'transactions/purchases.json',
    category: 'Transactions',
    permissions: { view: 'viewProcurement', manage: 'createProcurement' },
    dependencies: ['suppliers', 'items', 'chartOfAccounts'],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: true,
    supportsSearch: true,
    supportsReports: true,
    visibleInNavigation: true,
    navigationOrder: 90,
  },
  {
    id: 'customerPayments',
    displayName: 'Customer Payments',
    icon: CreditCard,
    collectionNames: ['customerPayments'],
    backupPath: 'transactions/customerPayments.json',
    category: 'Transactions',
    dependencies: ['customers', 'sales', 'cashLedger', 'ledgerEntries'],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'supplierPayments',
    displayName: 'Supplier Payments',
    icon: CreditCard,
    collectionNames: ['supplierPayments'],
    backupPath: 'transactions/supplierPayments.json',
    category: 'Transactions',
    dependencies: ['suppliers', 'purchases', 'cashLedger', 'ledgerEntries'],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'expenses',
    displayName: 'Expenses',
    icon: TrendingDown,
    routeKey: 'expenses',
    collectionNames: ['expenses'],
    backupPath: 'transactions/expenses.json',
    category: 'Transactions',
    permissions: { view: 'viewExpenses', manage: 'createExpense' },
    dependencies: ['expenseCategories', 'cashLedger', 'ledgerEntries'],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: true,
    supportsSearch: true,
    supportsReports: true,
    visibleInNavigation: true,
    navigationOrder: 110,
  },

  // --- ACCOUNTING MODULES ---
  {
    id: 'ledgerEntries',
    displayName: 'Ledger Entries',
    icon: FileText,
    collectionNames: ['ledgerEntries'],
    backupPath: 'accounting/ledgerEntries.json',
    category: 'Accounting',
    dependencies: ['chartOfAccounts'],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'cashLedger',
    displayName: 'Cash Ledger',
    icon: Database,
    collectionNames: ['cashLedger'],
    backupPath: 'accounting/cashLedger.json',
    category: 'Accounting',
    dependencies: ['chartOfAccounts'],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'capital',
    displayName: 'Capital',
    icon: Database,
    collectionNames: ['capital'],
    backupPath: 'accounting/capital.json',
    category: 'Accounting',
    dependencies: ['chartOfAccounts'],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'financialLogs',
    displayName: 'Financial Logs',
    icon: FileText,
    collectionNames: ['financialLogs'],
    backupPath: 'accounting/financialLogs.json',
    category: 'Accounting',
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },

  // --- SYSTEM MODULES ---
  {
    id: 'counters',
    displayName: 'Counters',
    icon: Binary,
    collectionNames: ['counters'],
    backupPath: 'system/counters.json',
    category: 'System',
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'logs',
    displayName: 'Logs',
    icon: FileText,
    collectionNames: ['logs'],
    backupPath: 'audit/logs.json',
    category: 'System',
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },
  {
    id: 'Logs',
    displayName: 'Audit Logs',
    icon: FileText,
    collectionNames: ['Logs'],
    backupPath: 'audit/Logs.json',
    category: 'System',
    dependencies: [],
    supportsBackup: true,
    supportsRestore: true,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: false,
  },

  // --- CORE & NAVIGATION-ONLY MODULES ---
  {
    id: 'dashboard',
    displayName: 'Dashboard',
    icon: LayoutDashboard,
    routeKey: 'dashboard',
    collectionNames: [],
    category: 'Core',
    dependencies: [],
    supportsBackup: false,
    supportsRestore: false,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: true,
    navigationOrder: 10,
  },
  {
    id: 'inventory',
    displayName: 'Inventory Desk',
    icon: Box,
    routeKey: 'inventory',
    collectionNames: ['items', 'products'],
    category: 'Master Data',
    permissions: { view: 'viewProducts' },
    dependencies: [],
    supportsBackup: false,
    supportsRestore: false,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: true,
    navigationOrder: 20,
  },
  {
    id: 'product_ledger',
    displayName: 'Stock Card',
    icon: RefreshCw,
    routeKey: 'product_ledger',
    collectionNames: ['items'],
    category: 'Accounting',
    permissions: { view: 'viewProducts' },
    dependencies: [],
    supportsBackup: false,
    supportsRestore: false,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: true,
    navigationOrder: 30,
  },
  {
    id: 'ledger',
    displayName: 'Due Ledger',
    icon: CreditCard,
    routeKey: 'ledger',
    collectionNames: ['customerPayments', 'supplierPayments'],
    category: 'Accounting',
    permissions: { view: 'viewPayments' }, // Let's check permissions later, but this maps exactly to App.tsx logic
    dependencies: [],
    supportsBackup: false,
    supportsRestore: false,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: true,
    navigationOrder: 60,
  },
  {
    id: 'reports',
    displayName: 'Reports',
    icon: BarChart3,
    routeKey: 'reports',
    collectionNames: [],
    category: 'System',
    permissions: { view: 'viewFinancialReports' },
    dependencies: [],
    supportsBackup: false,
    supportsRestore: false,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: true,
    navigationOrder: 100,
  },
  {
    id: 'balancesheet',
    displayName: 'Balance Sheet',
    icon: Scale,
    routeKey: 'balancesheet',
    collectionNames: ['ledgerEntries', 'chartOfAccounts'],
    category: 'Accounting',
    permissions: { view: 'viewFinancialReports' },
    dependencies: [],
    supportsBackup: false,
    supportsRestore: false,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: true,
    navigationOrder: 120,
  },
  {
    id: 'company_settings',
    displayName: 'Company Settings',
    icon: Settings,
    routeKey: 'company_settings',
    collectionNames: [],
    category: 'System',
    permissions: { view: 'viewSettings' }, // Handled specially in App.tsx: permissions.viewSettings || permissions.voidPayment
    dependencies: [],
    supportsBackup: false,
    supportsRestore: false,
    supportsDashboard: false,
    supportsSearch: false,
    supportsReports: false,
    visibleInNavigation: true,
    navigationOrder: 150,
  }
];

// --- HELPER FUNCTIONS ---

export function getModule(id: string): ModuleDefinition | undefined {
  return MODULE_REGISTRY.find(m => m.id === id);
}

export function getModules(): readonly ModuleDefinition[] {
  return MODULE_REGISTRY;
}

export function getVisibleModules(): ModuleDefinition[] {
  return MODULE_REGISTRY.filter(m => m.visibleInNavigation)
    .sort((a, b) => (a.navigationOrder ?? 999) - (b.navigationOrder ?? 999));
}

export function getBackupModules(): ModuleDefinition[] {
  return MODULE_REGISTRY.filter(m => m.supportsBackup);
}

export function getRestoreModules(): ModuleDefinition[] {
  return MODULE_REGISTRY.filter(m => m.supportsRestore);
}

export function getModuleDependencies(id: string): readonly string[] {
  const mod = getModule(id);
  return mod ? mod.dependencies : [];
}

export function getPermissionModules(): ModuleDefinition[] {
  return MODULE_REGISTRY.filter(m => m.permissions !== undefined);
}

export function getDashboardModules(): ModuleDefinition[] {
  return MODULE_REGISTRY.filter(m => m.supportsDashboard);
}
