import { ActivityLog, Supplier, Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Pro Display XDR 32"',
    sku: 'DISP-XDR-001',
    category: 'Electronics',
    purchasePrice: 2999.00,
    sellingPrice: 4999.00,
    currentStock: 3,
    minimumStockAlert: 5,
    supplierName: 'Apple Wholesale Corp',
    supplierEmail: 'orders@applewholesale.com',
    location: 'Warehouse A - Shelf B2',
    description: '32-inch Retina 6K display with 1,000,000:1 contrast ratio, extreme dynamic range (XDR), and superwide viewing angle.',
    createdDate: '2026-05-30T14:22:00Z',
    status: 'active'
  },
  {
    id: 'prod-2',
    name: 'MacBook Pro 16" M3 Max',
    sku: 'LAP-MBP-163',
    category: 'Electronics',
    purchasePrice: 2199.00,
    sellingPrice: 3499.00,
    currentStock: 12,
    minimumStockAlert: 8,
    supplierName: 'Apple Wholesale Corp',
    supplierEmail: 'orders@applewholesale.com',
    location: 'Warehouse A - Shelf B1',
    description: '16-inch liquid retina XDR screen, 36GB unified memory, 1TB SSD, M3 Max 14-core CPU and 30-core GPU.',
    createdDate: '2026-05-31T09:15:00Z',
    status: 'active'
  },
  {
    id: 'prod-3',
    name: 'Ergonomic Aeron Chair',
    sku: 'OFF-AER-102',
    category: 'Office Supplies',
    purchasePrice: 750.00,
    sellingPrice: 1295.00,
    currentStock: 6,
    minimumStockAlert: 4,
    supplierName: 'Herman Miller Direct',
    supplierEmail: 'supply@hermanmiller.com',
    location: 'Warehouse B - Room 1',
    description: 'PostureFit SL lumbar support, fully adjustable armrests, Tilt Limiter mechanism with seat angle adjustment, Graphite finish.',
    createdDate: '2026-05-28T11:45:00Z',
    status: 'active'
  },
  {
    id: 'prod-4',
    name: 'Mechanical Keychron Q1 Keyboard',
    sku: 'ACC-KEY-Q01',
    category: 'Accessories',
    purchasePrice: 110.00,
    sellingPrice: 189.00,
    currentStock: 42,
    minimumStockAlert: 15,
    supplierName: 'Keychron Distribution',
    supplierEmail: 'sales@keychrondist.com',
    location: 'Warehouse A - Shelf C4',
    description: 'Fully customizable mechanical keyboard, 75% layout, hot-swappable switches, CNC aluminum body, double-gasket design.',
    createdDate: '2026-06-01T08:00:00Z',
    status: 'active'
  },
  {
    id: 'prod-5',
    name: 'Sony WH-1000XM5 Headphones',
    sku: 'ACC-XM5-105',
    category: 'Accessories',
    purchasePrice: 240.00,
    sellingPrice: 399.00,
    currentStock: 0,
    minimumStockAlert: 10,
    supplierName: 'Sony Electronics B2B',
    supplierEmail: 'business@sony-electronics.com',
    location: 'Warehouse A - Shelf C10',
    description: 'Industry-leading noise-canceling headphones with auto-NC optimizer, 8 mics, and precise voice pickup system.',
    createdDate: '2026-05-25T16:30:00Z',
    status: 'active'
  },
  {
    id: 'prod-6',
    name: 'Patagonia Torrentshell Jacket',
    sku: 'APP-PAT-TOR',
    category: 'Apparel',
    purchasePrice: 95.00,
    sellingPrice: 179.00,
    currentStock: 24,
    minimumStockAlert: 10,
    supplierName: 'Patagonia Outfit Co',
    supplierEmail: 'wholesale@patagonia.com',
    location: 'Warehouse C - Rack 3',
    description: 'Simple and unpretentious 3-layer waterproof/breathable H2No Performance Standard shell for high comfort and performance.',
    createdDate: '2026-05-29T10:05:00Z',
    status: 'active'
  },
  {
    id: 'prod-7',
    name: 'Yeti Rambler Tumbler 30oz',
    sku: 'HOM-YET-30Z',
    category: 'Home & Kitchen',
    purchasePrice: 18.00,
    sellingPrice: 38.00,
    currentStock: 85,
    minimumStockAlert: 20,
    supplierName: 'Yeti Authorized Wholesalers',
    supplierEmail: 'support@yetiwholesale.org',
    location: 'Warehouse B - Room 2',
    description: 'Double-wall vacuum insulted tumbler with MagSlider lid, durable Duracoat color, stainless steel premium body.',
    createdDate: '2026-06-01T06:45:00Z',
    status: 'active'
  },
  {
    id: 'prod-8',
    name: 'Hydro Flask 32oz Water Bottle',
    sku: 'SPO-HYD-32B',
    category: 'Sports & Outdoors',
    purchasePrice: 22.00,
    sellingPrice: 44.95,
    currentStock: 110,
    minimumStockAlert: 30,
    supplierName: 'Cascade Outdoors Ltd',
    supplierEmail: 'orders@cascadeoutdoors.ca',
    location: 'Warehouse B - Room 3',
    description: 'Wide mouth vacuum insulated stainless steel water bottle with leakproof straw lid and flex strap handle.',
    createdDate: '2026-05-27T13:10:00Z',
    status: 'active'
  }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 's1',
    name: 'Apple Wholesale Corp',
    contactPerson: 'Sarah Jenkins',
    email: 'orders@applewholesale.com',
    phone: '+1 (800) 555-0199',
    category: 'Electronics',
  },
  {
    id: 's2',
    name: 'Herman Miller Direct',
    contactPerson: 'David Miller',
    email: 'supply@hermanmiller.com',
    phone: '+1 (800) 222-7744',
    category: 'Office Supplies',
  },
  {
    id: 's3',
    name: 'Keychron Distribution',
    contactPerson: 'Linus Chen',
    email: 'sales@keychrondist.com',
    phone: '+852 9876 5432',
    category: 'Accessories',
  },
  {
    id: 's4',
    name: 'Sony Electronics B2B',
    contactPerson: 'Kenji Sato',
    email: 'business@sony-electronics.com',
    phone: '+1 (888) 123-4567',
    category: 'Accessories',
  },
  {
    id: 's5',
    name: 'Patagonia Outfit Co',
    contactPerson: 'Elena Rostova',
    email: 'wholesale@patagonia.com',
    phone: '+1 (800) 654-3210',
    category: 'Apparel',
  }
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'l1',
    itemId: 'prod-4',
    itemName: 'Mechanical Keychron Q1 Keyboard',
    type: 'stock_change',
    description: 'Restocked 15 units of Keychron Q1 Keyboard',
    quantityDifference: 15,
    timestamp: '2026-06-01T08:00:00Z',
  },
  {
    id: 'l2',
    itemId: 'prod-5',
    itemName: 'Sony WH-1000XM5 Headphones',
    type: 'stock_change',
    description: 'Sold 10 units. Item stock is now zero.',
    quantityDifference: -10,
    timestamp: '2026-05-25T16:30:00Z',
  },
  {
    id: 'l3',
    itemId: 'prod-1',
    itemName: 'Pro Display XDR 32"',
    type: 'edit',
    description: 'Updated price from $4799 to $4999',
    timestamp: '2026-05-30T14:22:00Z',
  },
  {
    id: 'l4',
    itemId: 'prod-8',
    itemName: 'Hydro Flask 32oz Water Bottle',
    type: 'add',
    description: 'Added new item Hydro Flask 32oz Water Bottle to Sports & Outdoors',
    timestamp: '2026-05-27T13:10:00Z',
  }
];
